# Generated by Django 5.0.4 on 2024-05-22 07:05

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_capacitador', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos_capacitador', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('profesion', models.CharField(max_length=255, verbose_name='Profesión')),
                ('grado_academico', models.CharField(blank=True, choices=[('Bachiller', 'BACHILLER'), ('Magister', 'MAGISTER'), ('Doctor', 'DOCTOR')], max_length=15, null=True, verbose_name='Grado Académico')),
                ('descripcion_c', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('correo', models.EmailField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/capacitadores/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_cliente', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='system/images/clientes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_config', models.CharField(max_length=100, verbose_name='Nombre de la Configuracion')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor de la Configuración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_equipo', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('apellido_equipo', models.CharField(max_length=100, unique=True, verbose_name='Apellido')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='system/images/equipo/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('historia', models.TextField()),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_proyecto', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('descripcion_corta', models.TextField(max_length=240, verbose_name='Descripción Corta')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción Detallada')),
                ('fecha_de_proyecto', models.DateField(default=datetime.datetime.now, verbose_name='Fecha del Proyecto')),
                ('cliente', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cliente')),
                ('imagen', models.ImageField(upload_to='system/images/proyectos/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True, verbose_name='Nombre del servicio')),
                ('descripcion_servicio', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='system/images/servicios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_curso', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_de_inicio', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio')),
                ('horario', models.TextField(blank=True, null=True, verbose_name='Horario')),
                ('duracion', models.TextField(blank=True, null=True, verbose_name='Duración')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo')),
                ('temario', models.FileField(blank=True, null=True, upload_to='system/documentos/temarios/', verbose_name='Temario')),
                ('imagen', models.ImageField(upload_to='system/images/cursos/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('capacitador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.capacitador', verbose_name='Capacitador')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_ins', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos_ins', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=255, verbose_name='Correo')),
                ('profesion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profesión')),
                ('grado_academico', models.CharField(blank=True, choices=[('Bachiller', 'BACHILLER'), ('Magister', 'MAGISTER'), ('Doctor', 'DOCTOR')], max_length=15, null=True, verbose_name='Grado Académico')),
                ('consulta', models.TextField(verbose_name='Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.cursos', verbose_name='Seleccione el curso de su interes')),
            ],
        ),
    ]
