# Generated by Django 5.0.4 on 2024-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='historia',
            field=models.TextField(verbose_name='Acerca de'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='url_whatsapp',
            field=models.CharField(max_length=255, verbose_name='Url Whatsapp'),
        ),
    ]
