# Generated by Django 5.0.4 on 2024-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_servicios_estado_alter_compania_historia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
