# Generated by Django 5.0.4 on 2024-06-18 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_publicidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo_principal', models.CharField(blank=True, max_length=100, verbose_name='Titulo principal')),
                ('nombre_boton', models.CharField(blank=True, default='#', max_length=100, verbose_name='Nombre boton')),
                ('url_boton', models.URLField(verbose_name='Enlace boton')),
                ('sub_section_proyectos', models.TextField(blank=True, verbose_name='Subtitulo Seccion Proyectos')),
                ('sub_section_servicios', models.TextField(blank=True, verbose_name='Subtitulo Seccion Servicios')),
                ('sub_section_clientes', models.TextField(blank=True, verbose_name='Subtitulo Seccion Clientes')),
                ('sub_section_cursos', models.TextField(blank=True, verbose_name='Subtitulo Seccion Cursos')),
                ('imagen_principal_1', models.ImageField(upload_to='system/images/galeria/', verbose_name='Imagen Portada Principal 1')),
                ('imagen_principal_2', models.ImageField(upload_to='system/images/galeria/', verbose_name='Imagen Portada Principal 2')),
                ('imagen_principal_3', models.ImageField(upload_to='system/images/galeria/', verbose_name='Imagen Portada Principal 3')),
                ('imagen_mision', models.ImageField(upload_to='system/images/galeria/', verbose_name='Imagen Misión')),
                ('imagen_vision', models.ImageField(upload_to='system/images/galeria/', verbose_name='Imagen Visión')),
            ],
        ),
        migrations.DeleteModel(
            name='Publicidad',
        ),
    ]
