# Generated by Django 5.0.4 on 2024-06-18 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_galeria_delete_publicidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_servicio', models.CharField(max_length=100, unique=True, verbose_name='Nombre del tipo de servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicios',
            name='servicio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.tiposervicio', verbose_name='Seleciones un tipo de servicio'),
        ),
    ]
