# Generated by Django 5.0.4 on 2024-06-24 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_rename_nombre_servicio_tiposervicio_nombre_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='temario',
            field=models.FileField(blank=True, null=True, upload_to='system/documentos/temarios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='Temario'),
        ),
        migrations.AlterField(
            model_name='inscripciones',
            name='consulta',
            field=models.TextField(max_length=150, verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion_corta',
            field=models.TextField(blank=True, max_length=240, null=True, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion_detallada',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Detallada'),
        ),
    ]
