# Generated by Django 5.0.4 on 2024-06-27 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_remove_galeria_imagen_principal_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenServicios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(upload_to='system/images/servicios/')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='system.servicios')),
            ],
        ),
    ]
