# Generated by Django 5.0.4 on 2024-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_remove_servicios_imagen_imagenservicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenservicios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='system/images/servicios/'),
        ),
    ]
