# Generated by Django 5.0.4 on 2024-06-30 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_imagenservicios_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('texto', models.CharField(blank=True, max_length=255, verbose_name='Mensaje')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.cursos', verbose_name='Curso')),
            ],
        ),
    ]
