# Generated by Django 5.0.4 on 2024-06-30 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
