# Generated by Django 5.0.4 on 2024-07-02 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_rename_descripcion_detallada_proyectos_descripcion_proyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenproyectos',
            old_name='servicios',
            new_name='proyecto',
        ),
    ]
