# Generated by Django 5.0.4 on 2024-07-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_rename_servicios_imagenproyectos_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='servicio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.tiposervicio', verbose_name='Seleccione un tipo de servicio'),
        ),
    ]
